FROM python:3.12-alpine

WORKDIR /omadir

RUN apk add --no-cache curl ca-certificates && \
 curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
 chmod a+rx /usr/local/bin/yt-dlp && \
 adduser -D appuser && \
 chown appuser . && \
 apk del curl

USER appuser

ENTRYPOINT ["/usr/local/bin/yt-dlp"]